### ISSUE TITLE
Resize event listener should throttle or at least support it as an option

### ISSUE THREAD

**Issue by andreisebastianc** [calinortan/react-getscreen#1]
```
    componentDidMount() {
      if (options.shouldListenOnResize) {
        window.addEventListener('resize', this.onResize);
      }
}
```

The `resize` event is triggered constantly while the user is dragging the browser screen. This will end up in a noticeable lag.

**Comment by calinortan** [comment]
It is not that big of a deal as the render is triggered only when the breakpoints are reached.
However, fixed by [22b6eb2](https://github.com/calinortan/react-getscreen/commit/22b6eb2f55ad51404ea81752517f11438e2a051a)
